### ISSUE TITLE
How could I use the "public URL" feature with the minecraft server?

### ISSUE THREAD

**Issue by CactiChameleon9** [AlexProgrammerDE/balena-minecraft-server#26]
I am currently running a paper and geyser server to host a bedrock server (balena on a pi 4)... But I cannot get the public URL balena feature to work with bedrock minecraft. (It does work on local IP). I have my docker-compose.yml is like this:                           
```
version: '2'
services:
  mc-server:
    network_mode: host
    restart: always
    build: ./mcserver
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
      - "80:19132/udp"
      - "80:19132/tcp"
     # - "443:19132/tcp"
     # - "443:19132/ucp"
volumes:
  serverfiles:
  servercache: 



```

That should be making the geyser port of 19132 be on the host, 80 - the port used for public URL. 

I enter in the details:
![Screenshot_20200523_173242](https://user-images.githubusercontent.com/51231053/82735734-bc79d400-9d1b-11ea-9675-427ad1748fc9.png)

But it just does not connect - like it would normally if the server was offline... Yet I can connect to the local IP...
Any ideas/help?
